<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LBsEstados extends TActiveRecord
{
	const TABLE='bs_estados';

	public $id_estados;
	public $nombre;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}



	public function __toString() {
		return $this->nombre;
	}
}