<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LBsModulos extends TActiveRecord
{
	const TABLE='bs_modulos';

	public $id_modulos;
	public $nombre;
	public $descripcion;
	public $icon;
	public $css_class;
	public $orden;
	public $activo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_servicios' => array(self::HAS_MANY, 'LBsServicios', 'id_modulos')
	);

	public function __toString() {
		return $this->nombre;
	}
}