<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LBsPermisos extends TActiveRecord
{
	const TABLE='bs_permisos';

	public $id_permisos;
	public $nombre;
	public $activo;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_usuario_permiso' => array(self::HAS_MANY, 'LBsUsuarioPermiso', 'id_permisos')
	);

	public function __toString() {
		return $this->nombre;
	}
}