<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LBsRolesServicios extends TActiveRecord
{
	const TABLE='bs_roles_servicios';

	public $id_roles_servicios;
	public $id_roles;
	public $id_servicios;
	public $activo;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_roles' => array(self::BELONGS_TO, 'LBsRoles', 'id_roles'),
		'bs_servicios' => array(self::BELONGS_TO, 'LBsServicios', 'id_servicios')
	);

	public function __toString() {
		return $this->id_roles_servicios;
	}
}