<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LBsServicios extends TActiveRecord
{
	const TABLE='bs_servicios';

	public $id_servicios;
	public $nombre;
	public $descripcion;
	public $icon;
	public $css_class;
	public $page_form;
	public $page_print;
	public $page_export;
	public $param;
	public $permisos;
	public $id_modulos;
	public $activo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_roles_servicios' => array(self::HAS_MANY, 'LBsRolesServicios', 'id_servicios'),
		'bs_modulos' => array(self::BELONGS_TO, 'LBsModulos', 'id_modulos'),
		'bs_usuarios_servicios' => array(self::HAS_MANY, 'LBsUsuariosServicios', 'id_servicios')
	);

	public function __toString() {
		return $this->nombre;
	}
}