<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LBsUsuarios extends TActiveRecord
{
	const TABLE='bs_usuarios';

	public $id_usuarios;
	public $id_sucursales;
	public $foto;
	public $nombre;
	public $cargo;
	public $user;
	public $pass;
	public $correo;
	public $telefono;
	public $direccion;
	public $observaciones;
	public $id_roles;
	public $id_accesos;
	public $activo;
	public $descuento;
	public $borrado;
	public $permisos;
	public $cadena_referencia;
	public $fecha_alta;
	public $fecha_actualizado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_usuario_permiso' => array(self::HAS_MANY, 'LBsUsuarioPermiso', 'id_usuarios'),
		'bs_roles' => array(self::BELONGS_TO, 'LBsRoles', 'id_roles'),
		'ct_accesos' => array(self::BELONGS_TO, 'LCtAccesos', 'id_accesos'),
		'ct_sucursales' => array(self::BELONGS_TO, 'LCtSucursales', 'id_sucursales'),
		'bs_usuarios_activos' => array(self::HAS_MANY, 'LBsUsuariosActivos', 'id_usuarios'),
		'bs_usuarios_servicios' => array(self::HAS_MANY, 'LBsUsuariosServicios', 'id_usuarios'),
		'ct_folios_creditos' => array(self::HAS_MANY, 'LCtFoliosCreditos', 'id_usuarios'),
		'ms_cortes' => array(self::HAS_MANY, 'LMsCortes', 'id_usuarios'),
		'ms_movimientos' => array(self::HAS_MANY, 'LMsMovimientos', 'id_usuarios'),
		'ms_ventas' => array(self::HAS_MANY, 'LMsVentas', 'id_usuarios')
	);

	public function __toString() {
		return $this->foto;
	}
}