<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LBsUsuariosServicios extends TActiveRecord
{
	const TABLE='bs_usuarios_servicios';

	public $id_usuarios_servcios;
	public $id_usuarios;
	public $id_servicios;
	public $permisos;
	public $param;
	public $activo;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_usuarios' => array(self::BELONGS_TO, 'LBsUsuarios', 'id_usuarios'),
		'bs_servicios' => array(self::BELONGS_TO, 'LBsServicios', 'id_servicios')
	);

	public function __toString() {
		return $this->permisos;
	}
}