<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtAccesos extends TActiveRecord
{
	const TABLE='ct_accesos';

	public $id_accesos;
	public $id_sucursal;
	public $acceso;
	public $activo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'bs_usuarios' => array(self::HAS_MANY, 'LBsUsuarios', 'id_accesos'),
		'ct_sucursales' => array(self::BELONGS_TO, 'LCtSucursales', 'id_sucursal')
	);

	public function __toString() {
		return $this->acceso;
	}
}