<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtBodegas extends TActiveRecord
{
	const TABLE='ct_bodegas';

	public $id_bodegas;
	public $id_sucursales;
	public $bodega;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ct_sucursales' => array(self::BELONGS_TO, 'LCtSucursales', 'id_sucursales'),
		'ms_inventarios' => array(self::HAS_MANY, 'LMsInventarios', 'id_bodegas'),
		'ms_movimientos' => array(self::HAS_MANY, 'LMsMovimientos', 'id_bodegas')
	);

	public function __toString() {
		return $this->bodega;
	}
}