<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtCreditosAbonos extends TActiveRecord
{
	const TABLE='ct_creditos_abonos';

	public $id_creditos_abonos;
	public $id_clientes;
	public $id_ventas;
	public $id_usuarios;
	public $fecha_abono;
	public $monto;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}



	public function __toString() {
		return $this->fecha_abono;
	}
}