<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtCorteMovimientos extends TActiveRecord
{
	const TABLE='ct_corte_movimientos';

	public $id_corte_movimientos;
	public $id_cortes;
	public $id_ventas;
	public $id_ventasdetalle;
	public $borrado;
	public $fecha_movimiento;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_cortes' => array(self::BELONGS_TO, 'LMsCortes', 'id_cortes'),
		'ms_ventas' => array(self::BELONGS_TO, 'LMsVentas', 'id_ventas'),
		'ct_ventas_detalle' => array(self::BELONGS_TO, 'LCtVentasDetalle', 'id_ventasdetalle')
	);

	public function __toString() {
		return $this->fecha_movimiento;
	}
}