<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtCorteRetiros extends TActiveRecord
{
	const TABLE='ct_corte_retiros';

	public $id_corte_retiros;
	public $id_cortes;
	public $tipo;
	public $descripcion;
	public $monto;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_cortes' => array(self::BELONGS_TO, 'LMsCortes', 'id_cortes')
	);

	public function __toString() {
		return $this->descripcion;
	}
}