<?php
/**
 * Auto generated by PRADO - WSAT on 2019-07-27 01:55:16.
 * @author 
 */
class LCtCorteInventario extends TActiveRecord
{
	const TABLE='ct_corte_inventario';

	public $id_corte_inventario;
	public $id_cortes;
	public $id_inventario;
	public $id_productos;
	public $inicia;
	public $venta;
	public $merma;
	public $abasto;
	public $termina;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_inventarios' => array(self::BELONGS_TO, 'LMsInventarios', 'id_inventario'),
		'ms_productos' => array(self::BELONGS_TO, 'LMsProductos', 'id_productos'),
		'ms_cortes' => array(self::BELONGS_TO, 'LMsCortes', 'id_cortes')
	);

	public function __toString() {
		return $this->inicia;
	}
}