<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtCodigosreservados extends TActiveRecord
{
	const TABLE='ct_codigosreservados';

	public $id_codigosreservados;
	public $codigo;
	public $nombre;
	public $funcion;
	public $tipo;
	public $estatus;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}



	public function __toString() {
		return $this->codigo;
	}
}