<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtFoliosVentaCobrado extends TActiveRecord
{
	const TABLE='ct_folios_venta_cobrado';

	public $id_folios_venta_cobrado;
	public $id_ventas;
	public $id_folios_creditos;
	public $credito;
	public $estatus;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_ventas' => array(self::BELONGS_TO, 'LMsVentas', 'id_ventas'),
		'ct_folios_creditos' => array(self::BELONGS_TO, 'LCtFoliosCreditos', 'id_folios_creditos')
	);

	public function __toString() {
		return $this->credito;
	}
}