<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtFoliosCreditos extends TActiveRecord
{
	const TABLE='ct_folios_creditos';

	public $id_folios_creditos;
	public $id_cortes;
	public $id_ventas;
	public $id_usuarios;
	public $fecha_inicia;
	public $fecha_caducidad;
	public $fecha_creado;
	public $ticket;
	public $monto;
	public $estatus;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_ventas' => array(self::BELONGS_TO, 'LMsVentas', 'id_ventas'),
		'ms_cortes' => array(self::BELONGS_TO, 'LMsCortes', 'id_cortes'),
		'bs_usuarios' => array(self::BELONGS_TO, 'LBsUsuarios', 'id_usuarios'),
		'ct_folios_venta_cobrado' => array(self::HAS_MANY, 'LCtFoliosVentaCobrado', 'id_folios_creditos')
	);

	public function __toString() {
		return $this->fecha_creado;
	}
}