<?php
/**
 * Auto generated by PRADO - WSAT on 2019-07-22 06:41:13.
 * @author 
 */
class LCtProductoKit extends TActiveRecord
{
	const TABLE='ct_producto_kit';

	public $id_producto_kit;
	public $id_productos_main;
	public $id_producto_ingrediente;
	public $cantidad;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_productosmain' => array(self::BELONGS_TO, 'LMsProductos', 'id_productos_main'),
		'ms_productos' => array(self::BELONGS_TO, 'LMsProductos', 'id_producto_ingrediente')
	);

	public function __toString() {
		return $this->cantidad;
	}
}
