<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-31 03:52:25.
 * @author 
 */
class LCtProductoImpuestos extends TActiveRecord
{
	const TABLE='ct_producto_impuestos';

	public $id_producto_impuestos;
	public $id_productos;
	public $id_tasa_cuota;
	public $impuesto;
	public $valor;
	public $incluido;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_productos' => array(self::BELONGS_TO, 'LMsProductos', 'id_productos'),
		'sat_tasa_cuota' => array(self::BELONGS_TO, 'LSatTasaCuota', 'id_tasa_cuota')
	);

	public function __toString() {
		return $this->impuesto;
	}
}