<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtTickets extends TActiveRecord
{
	const TABLE='ct_tickets';

	public $id_tickets;
	public $id_sucursales;
	public $nombre;
	public $parametros;
	public $configuracion;
	public $activo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ct_sucursales' => array(self::BELONGS_TO, 'LCtSucursales', 'id_sucursales')
	);

	public function __toString() {
		return $this->nombre;
	}
}