<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LCtVentasDetalle extends TActiveRecord
{
	const TABLE='ct_ventas_detalle';

	public $id_ventas_detalle;
	public $id_ventas;
	public $id_inventarios;
	public $precio_publico;
	public $precio_adquisicion;
	public $precio_vendido;
	public $descuento;
	public $cantidad;
	public $fecha_movimiento;
	public $estatus;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ct_corte_movimientos' => array(self::HAS_MANY, 'LCtCorteMovimientos', 'id_ventasdetalle'),
		'ms_ventas' => array(self::BELONGS_TO, 'LMsVentas', 'id_ventas'),
		'ms_inventarios' => array(self::BELONGS_TO, 'LMsInventarios', 'id_inventarios')
	);

	public function __toString() {
		return $this->precio_publico;
	}
}