<?php
/**
 * Auto generated by PRADO - WSAT on 2019-07-09 06:00:24.
 * @author 
 */
class LMsClientes extends TActiveRecord
{
	const TABLE='ms_clientes';

	public $id_clientes;
	public $tipo_cliente;
	public $id_estados;
	public $id_municipios;
	public $rfc;
	public $nombre;
	public $telefono;
	public $direccion;
	public $referencia;
	public $mail;
	public $foto;
	public $credito;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_ventas' => array(self::HAS_MANY, 'LMsVentas', 'id_clientes')
	);

	public function __toString() {
		return $this->rfc;
	}
}