<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LMsCortes extends TActiveRecord
{
	const TABLE='ms_cortes';

	public $id_cortes;
	public $id_sucursal;
	public $id_usuarios;
	public $fecha_registro;
	public $fecha_inicio;
	public $fecha_final;
	public $estatus;
	public $inicio_caja;
	public $ventas_realizadas;
	public $gastos_realizados;
	public $entradas_adicionales;
	public $creditos;
	public $aportado_creditos;
	public $efectivo;
	public $tarjeta;
	public $cheque;
	public $trasferencia;
	public $otro;
	public $total;
	public $encaja;
	public $retiro_deposito;
	public $observaciones;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ct_corte_movimientos' => array(self::HAS_MANY, 'LCtCorteMovimientos', 'id_cortes'),
		'ct_corte_retiros' => array(self::HAS_MANY, 'LCtCorteRetiros', 'id_cortes'),
		'ct_folios_creditos' => array(self::HAS_MANY, 'LCtFoliosCreditos', 'id_cortes'),
		'ct_sucursales' => array(self::BELONGS_TO, 'LCtSucursales', 'id_sucursal'),
		'bs_usuarios' => array(self::BELONGS_TO, 'LBsUsuarios', 'id_usuarios'),
		'ms_ventas' => array(self::HAS_MANY, 'LMsVentas', 'id_cortes')
	);

	public function __toString() {
		return $this->fecha_registro;
	}
}