<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LMsContratos extends TActiveRecord
{
	const TABLE='ms_contratos';

	public $id_contratos;
	public $id_usuarios;
	public $id_tipo;
	public $logo;
	public $nombre;
	public $rfc;
	public $regimen_fiscal;
	public $razon_social;
	public $pagos;
	public $importe;
	public $telefono;
	public $fecha_inicio;
	public $fecha_final;
	public $estatus;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}



	public function __toString() {
		return $this->logo;
	}
}