<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LMsDescuento extends TActiveRecord
{
	const TABLE='ms_descuento';

	public $id_descuentos;
	public $id_producto;
	public $descuento;
	public $fecha_inicio;
	public $fecha_termina;
	public $duracion;
	public $estatus;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}



	public function __toString() {
		return $this->descuento;
	}
}