<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LMsMovimientos extends TActiveRecord
{
	const TABLE='ms_movimientos';

	public $id_movimientos;
	public $id_usuarios;
	public $id_sucursales;
	public $id_bodegas;
	public $tipo_movimiento;
	public $descripcion;
	public $fecha_registro;
	public $fecha_movimiento;
	public $fecha_actualizacion;
	public $estatus;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ct_movimientos_inventarios' => array(self::HAS_MANY, 'LCtMovimientosInventarios', 'id_movimientos'),
		'bs_usuarios' => array(self::BELONGS_TO, 'LBsUsuarios', 'id_usuarios'),
		'ct_sucursales' => array(self::BELONGS_TO, 'LCtSucursales', 'id_sucursales'),
		'ct_bodegas' => array(self::BELONGS_TO, 'LCtBodegas', 'id_bodegas')
	);

	public function __toString() {
		return $this->descripcion;
	}
}