<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LMsProductos extends TActiveRecord
{
	const TABLE='ms_productos';

	public $id_productos;
	public $foto;
	public $codigo;
	public $nombre;
	public $descripcion;
	public $tipo;
	public $id_departamentos;
	public $claveunidad;
	public $claveprodserv;
	public $borrado;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_inventarios' => array(self::HAS_MANY, 'LMsInventarios', 'id_productos'),
		'ct_departamentos' => array(self::BELONGS_TO, 'LCtDepartamentos', 'id_departamentos'),
		'sat_unidades' => array(self::BELONGS_TO, 'LSatUnidades', 'claveunidad'),
		'sat_productos_servicios' => array(self::BELONGS_TO, 'LSatProductosServicios', 'claveprodserv')
	);

	public function __toString() {
		return $this->foto;
	}
}