<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LMsVentas extends TActiveRecord
{
	const TABLE='ms_ventas';

	public $id_ventas;
	public $id_sucursales;
	public $id_cortes;
	public $id_clientes;
	public $id_usuarios;
	public $estatus;
	public $tipo_venta;
	public $modo_pago;
	public $fecha_inicio;
	public $fecha_termina;
	public $descuento;
	public $subtotal;
	public $total;
	public $venta;
	public $efectivo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ct_corte_movimientos' => array(self::HAS_MANY, 'LCtCorteMovimientos', 'id_ventas'),
		'ct_folios_creditos' => array(self::HAS_MANY, 'LCtFoliosCreditos', 'id_ventas'),
		'ct_folios_venta_cobrado' => array(self::HAS_MANY, 'LCtFoliosVentaCobrado', 'id_ventas'),
		'ct_ventas_detalle' => array(self::HAS_MANY, 'LCtVentasDetalle', 'id_ventas'),
		'ms_cortes' => array(self::BELONGS_TO, 'LMsCortes', 'id_cortes'),
		'ms_clientes' => array(self::BELONGS_TO, 'LMsClientes', 'id_clientes'),
		'bs_usuarios' => array(self::BELONGS_TO, 'LBsUsuarios', 'id_usuarios'),
		'ct_sucursales' => array(self::BELONGS_TO, 'LCtSucursales', 'id_sucursales')
	);

	public function __toString() {
		return $this->fecha_inicio;
	}
}