<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-29 04:19:22.
 * @author 
 */
class LSatTasaCuota extends TActiveRecord
{
	const TABLE='sat_tasa_cuota';

	public $id_tasa_cuota;
	public $nimpuesto;
	public $impuesto;
	public $tasa;
	public $factor;
	public $traslado;
	public $retencion;
	public $activo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}



	public function __toString() {
		return $this->nimpuesto;
	}
}