<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LSatUnidades extends TActiveRecord
{
	const TABLE='sat_unidades';

	public $claveunidad;
	public $nombre;
	public $descripcion;
	public $unidad;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_productos' => array(self::HAS_MANY, 'LMsProductos', 'claveunidad')
	);

	public function __toString() {
		return $this->nombre;
	}
}