<?php
/**
 * Auto generated by PRADO - WSAT on 2018-08-02 12:10:25.
 * @author 
 */
class LSatProductosServicios extends TActiveRecord
{
	const TABLE='sat_productos_servicios';

	public $claveprodserv;
	public $descripcion;
	public $similares;
	public $fecha;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}

	public static $RELATIONS = array (
		'ms_productos' => array(self::HAS_MANY, 'LMsProductos', 'claveprodserv')
	);

	public function __toString() {
		return $this->descripcion;
	}
}